#!/bin/sh

cwd=$(pwd)
name="Nimiq-Safe-offline"

echo "Checking out offline branches"

cd libraries/keyguard
git checkout offline
cd $cwd

cd libraries/secure-utils
git checkout offline
cd $cwd

echo "Building Safe and Keyguard deployment"

cd apps/safe
gulp
cd $cwd

cd libraries/keyguard
gulp
cd $cwd

echo "Packaging $name.zip"

mkdir $name
mkdir $name/safe
mkdir $name/keyguard

cp apps/safe/deployment-safe/dist/* $name/safe/
cp libraries/keyguard/deployment-keyguard/dist/* $name/keyguard/

rm $name.zip
zip -r $name.zip $name

echo "Cleaning up"
rm -r $name

cd libraries/keyguard
git checkout master
cd $cwd

cd libraries/secure-utils
git checkout master
cd $cwd
