#!/bin/sh

cwd=$(pwd)
name="Nimiq-Safe-offline"

echo "Checking out offline branches"

# Use local Nimiq.js in Keyguard
cd libraries/keyguard
git checkout offline
cd $cwd

# Checkout offline Config
cd libraries/secure-utils
git checkout offline
cd $cwd

echo "Building offline Safe and Keyguard deployments"

cd apps/safe
gulp
cd $cwd

cd libraries/keyguard
gulp
cd $cwd

echo "Packaging $name.zip"

mkdir $name
mkdir $name/safe
mkdir $name/keyguard

cp apps/safe/deployment-safe/dist/* $name/safe/
cp libraries/keyguard/deployment-keyguard/dist/* $name/keyguard/

rm $name.zip
zip -r $name.zip $name

echo "Cleaning up"
rm -r $name

# Switch back from offline to to master branches
cd libraries/keyguard
git checkout master
cd $cwd

cd libraries/secure-utils
git checkout master
cd $cwd

echo "Done"
